title: Francesca Bottenghi
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Dedicated Journalist with experience creating original and engaging content 
  for leading media groups. Proven expertise in researching, planning, editing, 
  proofreading, and delivering final texts for both print and online 
  distribution. Leverages attention to detail and exemplary organization and 
  time management skills to consistently meet deadlines. Dependable 
  professional keen on learning and implementing new skills. Analytical, 
  diplomatic problem-solver adept at working autonomously as well as in teams. 
  Excellent interpersonal skills with ability to communicate with diverse 
  audiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fbottenghi
instagram_username: fbottenghi
linkedin_username: francescabottenghi

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
