title: Francesca Bottenghi
description: 
url: "https://francescabottenghi.com"
twitter_username: fbottenghi
instagram_username: fbottenghi
linkedin_username: francescabottenghi

# Build settings
markdown: kramdown

# Other settings
permalink: /:categories/:title/

# Default excludes
exclude:
- .jekyll-cache
- Gemfile
- Gemfile.lock
- README.md
